version: '3.1'
services:
    mysql:
        image: 'mysql:latest'
        working_dir: /application
        restart: always
        volumes:
            - '..:/application'
        environment:
            - MYSQL_ROOT_PASSWORD=1234
            - MYSQL_DATABASE=dbteste
            - MYSQL_PASSWORD=1234
        ports:
            - '3003:3306'

    webserver:
        image: 'nginx:alpine'
        working_dir: /application
        volumes:
            - '..:/application'
            - './nginx/nginx.conf:/etc/nginx/conf.d/default.conf'
        ports:
            - '3000:80'

    php-fpm:
        build: php-fpm
        working_dir: /application
        volumes:
            - '..:/application'
            - './php-fpm/php-ini-overrides.ini:/etc/php/8.1/fpm/conf.d/99-overrides.ini'

    phpmyadmin:
        image: phpmyadmin
        container_name: phpmyadmin
        restart: always
        ports:
            - 8888:80
        environment:
            - PMA_HOST=mysql
            - PMA_ROOT_PASSWORD=1234
            - PMA_PASSWORD=1234
volumes:
    mysql: